version: '3.8'

services:
  myapp:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/bot
  db:
    image: postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
#    volumes:
#      - postgres_data:/var/lib/postgresql/data  # Позволяет сохранять данные базы данных между запусками
#    restart: always
#volumes:
#  postgres_data:
